# Generated by Django 4.0.3 on 2022-04-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
