# Generated by Django 4.0.3 on 2022-04-08 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking_id', models.CharField(max_length=256)),
                ('total_price', models.IntegerField()),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=64, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('admission_number', models.CharField(blank=True, max_length=256, null=True)),
                ('branch', models.CharField(blank=True, max_length=200, null=True)),
                ('is_purchased', models.BooleanField(db_index=True, default=False)),
                ('is_mail_send', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.booking')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_management.product')),
            ],
        ),
    ]
