# Generated by Django 4.0.3 on 2022-05-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitems',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookingitems',
            name='unit_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
